import { randomInt } from "node:crypto";
import { Prisma, type BookingSource } from "@prisma/client";
import { db } from "@/lib/db";
import { eachNight, toUTCDate } from "@/lib/dates";
import { buildQuote } from "@/lib/pricing/engine";
import { getNotificationProvider } from "@/lib/notifications/provider";
import { renderTemplate } from "@/lib/notifications/templates";
import { alertTeam } from "@/lib/notifications/alert";
import { enqueueChannelSync } from "@/lib/queue";

export class InventoryConflictError extends Error {
  constructor() {
    super("Those dates were just taken. Please pick different dates.");
    this.name = "InventoryConflictError";
  }
}

export type CreateReservationInput = {
  propertyId: string;
  unitId?: string;
  checkIn: Date;
  checkOut: Date;
  adults: number;
  children?: number;
  guest: { name: string; email?: string | null; phone?: string | null };
  source?: BookingSource;
  userId?: string | null;
};

const CODE_ALPHABET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";

// This code is a public, unauthenticated lookup key for
// /booking-confirmation/[code] (see that page - it renders guest PII to
// whoever holds the code, no session required). Math.random() and a 4-char
// suffix made that lookup key brute-forceable (36^4 ≈ 1.7M combinations,
// generated by a non-cryptographic PRNG); crypto.randomInt plus a 6-char
// suffix (36^6 ≈ 2.2B) makes guessing one impractical. The page also now
// rate-limits by IP as the primary defence - this is defence in depth.
function generateCode() {
  let rand = "";
  for (let i = 0; i < 6; i++) {
    rand += CODE_ALPHABET[randomInt(0, CODE_ALPHABET.length)];
  }
  return `LK-${new Date().getFullYear()}${rand}`;
}

/** OTA commission rates used to record the fee side of channel bookings. */
const OTA_FEE_RATES: Partial<Record<BookingSource, number>> = {
  AIRBNB: 0.14,
  BOOKING_COM: 0.15,
  AGODA: 0.16,
};

/**
 * The one path that creates a booking. Availability check, inventory lock
 * and reservation creation happen inside a single transaction - the unique
 * constraint on (unitId, date) is what actually guarantees no double-booking
 * under concurrency.
 *
 * There's no payment gateway wired up right now, so this only ever files a
 * booking *request*: the reservation starts (and stays) PENDING, holding the
 * dates, and the guest is told our team will reach out to arrange payment.
 * Revenue is posted later, once someone on the team confirms the reservation
 * (see confirmReservation) after that payment is actually in hand.
 */
export async function createReservation(input: CreateReservationInput) {
  const checkIn = toUTCDate(input.checkIn);
  const checkOut = toUTCDate(input.checkOut);
  const nights = eachNight(checkIn, checkOut);

  if (nights.length === 0) {
    throw new Error("Checkout must be at least one night after check-in.");
  }

  const property = await db.property.findUniqueOrThrow({
    where: { id: input.propertyId },
    include: { units: true, pricingRules: { where: { isActive: true } } },
  });

  const unitId = input.unitId ?? property.units[0]?.id;
  if (!unitId) throw new Error("This property has no bookable unit.");

  const overrides = await db.dailyRate.findMany({
    where: { propertyId: property.id, date: { gte: checkIn, lt: checkOut } },
  });

  const quote = buildQuote({
    basePrice: Number(property.basePrice),
    cleaningFee: Number(property.cleaningFee),
    checkIn,
    checkOut,
    rules: property.pricingRules,
    dailyRateOverrides: Object.fromEntries(
      overrides.map((o) => [o.date.toISOString().slice(0, 10), Number(o.price)]),
    ),
  });

  const source = input.source ?? "DIRECT";
  const code = generateCode();

  const reservation = await db
    .$transaction(async (tx) => {
      const guest = await upsertGuest(tx, input.guest, input.userId ?? null);

      const created = await tx.reservation.create({
        data: {
          code,
          propertyId: property.id,
          unitId,
          guestId: guest.id,
          checkIn,
          checkOut,
          adults: input.adults,
          children: input.children ?? 0,
          status: "PENDING",
          source,
          nightlyRate: new Prisma.Decimal(quote.averageNightlyRate),
          nights: quote.nightCount,
          subtotal: new Prisma.Decimal(quote.subtotal),
          cleaningFee: new Prisma.Decimal(quote.cleaningFee),
          taxes: new Prisma.Decimal(quote.taxes),
          discount: new Prisma.Decimal(quote.discount),
          total: new Prisma.Decimal(quote.total),
          reservationGuests: {
            create: {
              name: input.guest.name,
              email: input.guest.email ?? null,
              phone: input.guest.phone ?? null,
              isPrimary: true,
            },
          },
        },
      });

      // Locking inventory: unique (unitId, date) rejects any concurrent booking
      // that overlaps even a single night.
      await tx.inventoryNight.createMany({
        data: nights.map((date) => ({
          unitId,
          date,
          reservationId: created.id,
        })),
      });

      return created;
    })
    .catch((error) => {
      if (
        error instanceof Prisma.PrismaClientKnownRequestError &&
        error.code === "P2002"
      ) {
        throw new InventoryConflictError();
      }
      throw error;
    });

  // The reservation is already committed at this point - the guest's request
  // has succeeded. Channel-sync push and the confirmation email/team alert
  // are side effects the guest is not waiting on; the caller runs this via
  // `after()` so a slow (or, with Redis down, up to ~4s-timed-out) sync push
  // or a flaky email API can no longer delay the response, or worse, make a
  // booking that actually succeeded come back as a 500.
  const notify = async () => {
    await notifyChannelsOfAvailabilityChange(property.id);
    try {
      await notifyGuestBookingRequested({
        reservationId: reservation.id,
        code: reservation.code,
        total: Number(reservation.total),
        guest: {
          name: input.guest.name,
          email: input.guest.email ?? null,
          phone: input.guest.phone ?? null,
        },
        propertyName: property.name,
        checkIn: reservation.checkIn,
        checkOut: reservation.checkOut,
        nights: reservation.nights,
        adults: reservation.adults,
        children: reservation.children,
        locationArea: property.locationArea,
        city: property.city,
      });
    } catch (error) {
      console.error("Failed to notify guest/team of new booking request", error);
    }
  };

  return {
    reservation,
    quote,
    status: "PENDING" as const,
    notify,
  };
}

type TxClient = Prisma.TransactionClient;

async function upsertGuest(
  tx: TxClient,
  guest: CreateReservationInput["guest"],
  userId: string | null,
) {
  const existing = await tx.guest.findFirst({
    where: {
      OR: [
        guest.email ? { email: guest.email } : undefined,
        guest.phone ? { phone: guest.phone } : undefined,
      ].filter(Boolean) as Prisma.GuestWhereInput[],
    },
  });

  if (existing) {
    return tx.guest.update({
      where: { id: existing.id },
      data: {
        name: guest.name,
        email: guest.email ?? existing.email,
        phone: guest.phone ?? existing.phone,
        userId: existing.userId ?? userId,
      },
    });
  }

  return tx.guest.create({
    data: {
      name: guest.name,
      email: guest.email ?? null,
      phone: guest.phone ?? null,
      userId,
    },
  });
}

/** Revenue plus its OTA/payment fees are posted as separate transactions. */
async function postBookingFinancials(
  tx: TxClient,
  args: {
    propertyId: string;
    reservationId: string;
    total: number;
    source: BookingSource;
    date: Date;
  },
) {
  const revenueCategory = await tx.transactionCategory.findFirstOrThrow({
    where: { group: "REVENUE", name: "Accommodation" },
  });

  await tx.transaction.create({
    data: {
      propertyId: args.propertyId,
      categoryId: revenueCategory.id,
      reservationId: args.reservationId,
      type: "REVENUE",
      amount: new Prisma.Decimal(args.total),
      date: args.date,
      status: "PAID",
      // Collected offline by the team, not through a gateway, so the actual
      // method isn't known here.
      paymentMethod: "OTHER",
      description: `Booking revenue · ${args.source}`,
    },
  });

  const otaRate = OTA_FEE_RATES[args.source];
  if (otaRate) {
    const otaCategory = await tx.transactionCategory.findFirstOrThrow({
      where: { group: "OTA_FEE" },
    });
    await tx.transaction.create({
      data: {
        propertyId: args.propertyId,
        categoryId: otaCategory.id,
        reservationId: args.reservationId,
        type: "OTA_FEE",
        amount: new Prisma.Decimal(Math.round(args.total * otaRate)),
        date: args.date,
        status: "PAID",
        description: `${args.source} commission`,
      },
    });
  }
}

/** A booking (or its cancellation) changes which nights are free, so every
 * OTA this property is linked to needs its calendar pushed again. Never
 * blocks the caller. */
async function notifyChannelsOfAvailabilityChange(propertyId: string) {
  try {
    const links = await db.channelProperty.findMany({
      where: { propertyId, externalListingId: { not: null } },
      select: { id: true },
    });
    await Promise.all(
      links.map((link) =>
        enqueueChannelSync({ channelPropertyId: link.id, reason: "AVAILABILITY_CHANGED" }),
      ),
    );
  } catch (error) {
    console.error("Failed to enqueue channel sync after booking", error);
  }
}

/**
 * Called once payment has actually settled - synchronously for the mock
 * provider, or from the Razorpay checkout-confirm route / webhook once a
 * real charge is captured. Idempotent: a reservation that isn't still
 * PENDING has already been confirmed (or cancelled) and is left alone, so
 * a client-side confirm racing the webhook can't double-post revenue.
 */
export async function confirmReservation(reservationId: string) {
  const reservation = await db.reservation.findUnique({
    where: { id: reservationId },
    include: {
      property: {
        select: {
          id: true,
          name: true,
          locationArea: true,
          city: true,
          images: { orderBy: { sortOrder: "asc" }, take: 1 },
        },
      },
      reservationGuests: { where: { isPrimary: true } },
      payments: true,
    },
  });
  if (!reservation || reservation.status !== "PENDING") return;

  await db.$transaction(async (tx) => {
    await tx.reservation.update({
      where: { id: reservation.id },
      data: { status: "CONFIRMED" },
    });
    await tx.reservationPayment.updateMany({
      where: { reservationId: reservation.id, status: "PENDING" },
      data: { status: "SUCCEEDED" },
    });
    await postBookingFinancials(tx, {
      propertyId: reservation.propertyId,
      reservationId: reservation.id,
      total: Number(reservation.total),
      source: reservation.source,
      date: reservation.checkIn,
    });
  });

  const primaryGuest = reservation.reservationGuests[0];
  await notifyGuestBookingConfirmed({
    reservationId: reservation.id,
    code: reservation.code,
    total: Number(reservation.total),
    guest: {
      name: primaryGuest?.name ?? "Guest",
      email: primaryGuest?.email ?? null,
      phone: primaryGuest?.phone ?? null,
    },
    propertyName: reservation.property.name,
    checkIn: reservation.checkIn,
    checkOut: reservation.checkOut,
    nights: reservation.nights,
    adults: reservation.adults,
    children: reservation.children,
    locationArea: reservation.property.locationArea,
    city: reservation.property.city,
    propertyImageUrl: reservation.property.images[0]?.url,
    paymentMethod: reservation.payments[0]?.method,
  });
}

/** Releases a PENDING reservation's hold on inventory - used both when an
 * intent fails to even start, and by the reservation-expiry worker job.
 * Returns false if there was nothing to release (already confirmed or
 * already cancelled), so callers can tell a real release from a no-op. */
export async function releasePendingReservation(reservationId: string): Promise<boolean> {
  const reservation = await db.reservation.findUnique({
    where: { id: reservationId },
    select: { id: true, status: true, propertyId: true },
  });
  if (!reservation || reservation.status !== "PENDING") return false;

  await db.$transaction([
    db.inventoryNight.deleteMany({ where: { reservationId: reservation.id } }),
    db.reservation.update({ where: { id: reservation.id }, data: { status: "CANCELLED" } }),
    db.reservationPayment.updateMany({
      where: { reservationId: reservation.id, status: "PENDING" },
      data: { status: "FAILED" },
    }),
  ]);

  await notifyChannelsOfAvailabilityChange(reservation.propertyId);
  return true;
}

/**
 * Admin-triggered cancellation - unlike releasePendingReservation (which only
 * ever fires against a PENDING hold), this also covers walking back a
 * CONFIRMED booking the guest can no longer take. Either way the inventory
 * hold is released and the guest is told. It does NOT touch any revenue
 * already posted for a confirmed booking - reversing that is a finance-team
 * call, made through the normal transaction tools, not an automatic one.
 * Returns false if there was nothing to cancel (already cancelled, or a
 * historical COMPLETED/NO_SHOW record).
 */
export async function cancelReservation(reservationId: string): Promise<boolean> {
  const reservation = await db.reservation.findUnique({
    where: { id: reservationId },
    include: {
      property: { select: { id: true, name: true } },
      reservationGuests: { where: { isPrimary: true } },
    },
  });
  if (!reservation || (reservation.status !== "PENDING" && reservation.status !== "CONFIRMED")) {
    return false;
  }
  const wasConfirmed = reservation.status === "CONFIRMED";

  await db.$transaction([
    db.inventoryNight.deleteMany({ where: { reservationId: reservation.id } }),
    db.reservation.update({ where: { id: reservation.id }, data: { status: "CANCELLED" } }),
    db.reservationPayment.updateMany({
      where: { reservationId: reservation.id, status: "PENDING" },
      data: { status: "FAILED" },
    }),
  ]);

  await notifyChannelsOfAvailabilityChange(reservation.propertyId);

  const primaryGuest = reservation.reservationGuests[0];
  await notifyGuestBookingCancelled({
    reservationId: reservation.id,
    code: reservation.code,
    guest: {
      name: primaryGuest?.name ?? "Guest",
      email: primaryGuest?.email ?? null,
      phone: primaryGuest?.phone ?? null,
    },
    propertyName: reservation.property.name,
    checkIn: reservation.checkIn,
    checkOut: reservation.checkOut,
    wasConfirmed,
  });

  return true;
}

async function notifyGuestBookingConfirmed(args: {
  reservationId: string;
  code: string;
  total: number;
  guest: { name: string; email?: string | null; phone?: string | null };
  propertyName: string;
  checkIn: Date;
  checkOut: Date;
  nights: number;
  adults: number;
  children: number;
  locationArea: string;
  city: string;
  propertyImageUrl?: string;
  paymentMethod?: string;
}) {
  const rendered = renderTemplate("BOOKING_CONFIRMED", {
    guestName: args.guest.name,
    propertyName: args.propertyName,
    checkIn: args.checkIn,
    checkOut: args.checkOut,
    bookingCode: args.code,
    total: args.total,
    nights: args.nights,
    adults: args.adults,
    children: args.children,
    locationArea: args.locationArea,
    city: args.city,
    propertyImageUrl: args.propertyImageUrl,
    paymentMethod: args.paymentMethod,
  });

  const notifier = getNotificationProvider();
  const destination = args.guest.email ?? args.guest.phone;
  if (destination) {
    const result = await notifier.send({
      channel: args.guest.email ? "EMAIL" : "WHATSAPP",
      to: destination,
      subject: rendered.subject,
      body: rendered.body,
      html: args.guest.email ? rendered.html : undefined,
      templateKey: "BOOKING_CONFIRMED",
    });

    await db.message.create({
      data: {
        reservationId: args.reservationId,
        channel: args.guest.email ? "EMAIL" : "WHATSAPP",
        direction: "OUTBOUND",
        templateKey: "BOOKING_CONFIRMED",
        subject: rendered.subject,
        body: rendered.body,
        status: result.status === "SENT" ? "SENT" : "FAILED",
        sentAt: new Date(),
      },
    });
  }

  await alertTeam({
    type: "NEW_BOOKING",
    title: "New booking confirmed",
    body: `${args.guest.name} booked ${args.propertyName} · ${args.code}`,
    severity: "INFO",
    link: `/admin/reservations?code=${args.code}`,
  });
}

/** Sent right after a guest submits a booking request - there's no payment
 * gateway wired up, so this is what stands in for a confirmation until
 * someone on the team reaches out and confirmReservation() finalizes it. */
async function notifyGuestBookingRequested(args: {
  reservationId: string;
  code: string;
  total: number;
  guest: { name: string; email?: string | null; phone?: string | null };
  propertyName: string;
  checkIn: Date;
  checkOut: Date;
  nights: number;
  adults: number;
  children: number;
  locationArea: string;
  city: string;
}) {
  const rendered = renderTemplate("BOOKING_REQUESTED", {
    guestName: args.guest.name,
    propertyName: args.propertyName,
    checkIn: args.checkIn,
    checkOut: args.checkOut,
    bookingCode: args.code,
    total: args.total,
    nights: args.nights,
    adults: args.adults,
    children: args.children,
    locationArea: args.locationArea,
    city: args.city,
  });

  const notifier = getNotificationProvider();
  const destination = args.guest.email ?? args.guest.phone;
  if (destination) {
    const result = await notifier.send({
      channel: args.guest.email ? "EMAIL" : "WHATSAPP",
      to: destination,
      subject: rendered.subject,
      body: rendered.body,
      html: args.guest.email ? rendered.html : undefined,
      templateKey: "BOOKING_REQUESTED",
    });

    await db.message.create({
      data: {
        reservationId: args.reservationId,
        channel: args.guest.email ? "EMAIL" : "WHATSAPP",
        direction: "OUTBOUND",
        templateKey: "BOOKING_REQUESTED",
        subject: rendered.subject,
        body: rendered.body,
        status: result.status === "SENT" ? "SENT" : "FAILED",
        sentAt: new Date(),
      },
    });
  }

  await alertTeam({
    type: "NEW_BOOKING",
    title: "New booking request",
    body: `${args.guest.name} requested ${args.propertyName} · ${args.code} - reach out to arrange payment.`,
    severity: "INFO",
    link: `/admin/reservations?code=${args.code}`,
  });
}

async function notifyGuestBookingCancelled(args: {
  reservationId: string;
  code: string;
  guest: { name: string; email?: string | null; phone?: string | null };
  propertyName: string;
  checkIn: Date;
  checkOut: Date;
  wasConfirmed: boolean;
}) {
  const rendered = renderTemplate("BOOKING_CANCELLED", {
    guestName: args.guest.name,
    propertyName: args.propertyName,
    checkIn: args.checkIn,
    checkOut: args.checkOut,
    bookingCode: args.code,
  });

  const notifier = getNotificationProvider();
  const destination = args.guest.email ?? args.guest.phone;
  if (destination) {
    const result = await notifier.send({
      channel: args.guest.email ? "EMAIL" : "WHATSAPP",
      to: destination,
      subject: rendered.subject,
      body: rendered.body,
      templateKey: "BOOKING_CANCELLED",
    });

    await db.message.create({
      data: {
        reservationId: args.reservationId,
        channel: args.guest.email ? "EMAIL" : "WHATSAPP",
        direction: "OUTBOUND",
        templateKey: "BOOKING_CANCELLED",
        subject: rendered.subject,
        body: rendered.body,
        status: result.status === "SENT" ? "SENT" : "FAILED",
        sentAt: new Date(),
      },
    });
  }

  await alertTeam({
    type: "NEW_BOOKING",
    title: "Booking cancelled",
    body: `${args.code} for ${args.propertyName} was cancelled${
      args.wasConfirmed ? " (was confirmed - check whether a refund is owed)" : ""
    }.`,
    severity: "WARNING",
    link: `/admin/reservations?code=${args.code}`,
  });
}
