ALTER TABLE "Reservation"
ADD COLUMN "platformFee" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN "hostTax" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN "otherCharges" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN "hasCustomFinancials" BOOLEAN NOT NULL DEFAULT false;